### ISSUE TITLE
ScriptParser-script/createTask.js脚本解析错误:任务信息采集不完整：名称、封面、数目不能为空 

### ISSUE THREAD

**Issue by UdongeinL** [dipoo/egdownloader#40]
在某次重启后Chrome告知我设置已被更改并且发现所有cookie都被清空
在重新验证进里站后无论创建新任务还是继续老任务都会出现如标题所示错误
老任务会报错红字：获取图片下载地址为空
版本0.95.11

**Comment by dipoo** [comment]
你是在下载器中使用了自己账号的 cookie 吗？
是的话就重新设置下吧。
这种情况就是没有获取到有效的 HTML 数据，具体可以在 source 目录下打开文件查看。

**Comment by UdongeinL** [comment]
下载器使用的是原本的cookie
我刚才看了source下面三个html文件打开都是被ban了一天IP的状态，时间还不尽相同，但是当时我连里站是没有被ban的，比较迷惑
我过一天换个节点尝试一下看看还会不会有一样的情况

**Comment by Asimodis** [comment]
昨天开始遇到同样的问题 使用vpn换ip无法解决

**Comment by Asimodis** [comment]
下新的压缩包打开就会弹这个 
an error has occurred during startup：

java.lang.ExceptionInInitializerError
	at org.arong.egdownloader.ui.window.InitWindow.<init>(InitWindow.java:123)
	at org.arong.egdownloader.ui.Main.main(Main.java:66)
	at org.arong.egdownloader.Startup.main(Startup.java:7)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:62)
	at com.exe4j.runtime.WinLauncher.main(WinLauncher.java:101)
Caused by: java.lang.NullPointerException
	at org.arong.util.JdbcSqlExecutor.executeUpdate(JdbcSqlExecutor.java:76)
	at org.arong.util.JdbcSqlExecutor.executeUpdate(JdbcSqlExecutor.java:58)
	at org.arong.egdownloader.db.impl.TaskSqliteDbTemplate.<clinit>(TaskSqliteDbTemplate.java:53)
	... 9 more

**Comment by Asimodis** [comment]
昨天开始遇到同样的问题 使用vpn换ip无法解决
 

下新的压缩包打开弹这个
启动时出现错误：

java.lang.ExceptionInInitializerError
at org.arong.egdownloader.ui.window.InitWindow.(InitWindow.java:123)
at org.arong.egdownloader.ui.Main.main(Main.java:66)
at org.arong.egdownloader .Startup.main(Startup.java:7)
at sun.reflect.NativeMethodAccessorImpl.invoke0( Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java) :43)
在 java.lang.reflect.Method.invoke(Method.java:606)
在 com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:62)
在 com.exe4j.runtime.WinLauncher.main(WinLauncher. java:101)
引起：java.lang.NullPointerException
在 org.arong.util.JdbcSqlExecutor.executeUpdate(JdbcSqlExecutor.java:76)
在 org.arong.util.JdbcSqlExecutor.executeUpdate(JdbcSqlExecutor.java:58)
在 org.arong.egdownloader.db.impl.TaskSqliteDbTemplate.(TaskSqliteDbTemplate. (TaskSqliteDbTemplate) java:53)
... 9 更多

**Comment by Asimodis** [comment]
> 你是在下载器中使用了账号的cookie吗？
> 是的话就重新设置一下吧。
> 这种情况就是没有获取到有效的HTML数据，具体可以在源码目录下打开文件查看。

昨天开始遇到同样的问题 使用vpn换ip无法解决
 

下新的压缩包打开弹这个
启动时出现错误：

java.lang.ExceptionInInitializerError
at org.arong.egdownloader.ui.window.InitWindow.(InitWindow.java:123)
at org.arong.egdownloader.ui.Main.main(Main.java:66)
at org.arong.egdownloader .Startup.main(Startup.java:7)
at sun.reflect.NativeMethodAccessorImpl.invoke0( Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java) :43)
在 java.lang.reflect.Method.invoke(Method.java:606)
在 com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:62)
在 com.exe4j.runtime.WinLauncher.main(WinLauncher. java:101)
引起：java.lang.NullPointerException
在 org.arong.util.JdbcSqlExecutor.executeUpdate(JdbcSqlExecutor.java:76)
在 org.arong.util.JdbcSqlExecutor.executeUpdate(JdbcSqlExecutor.java:58)
在 org.arong.egdownloader.db.impl.TaskSqliteDbTemplate.(TaskSqliteDbTemplate. (TaskSqliteDbTemplate) java:53)
... 9 更多

**Comment by dipoo** [comment]
@Asimodis 你看了 HTML 文件了吗？里面什么内容。

**Comment by dipoo** [comment]
@Asimodis 你这是正常的呀，与 issue 的问题不一样。

**Comment by dipoo** [comment]
> @Asimodis 你这是正常的呀，与 issue 的问题不一样。

这位兄弟账号被 github 删了，估计刚才回的 HTML 内容评论被系统检测为垃圾内容，各位以后还是截图吧

**Comment by guhuibanfan-ex** [comment]
> > @Asimodis 你这是正常的呀，与 issue 的问题不一样。
> 
> 这位兄弟账号被 github 删了，估计刚才回的 HTML 内容评论被系统检测为垃圾内容，各位以后还是截图吧

换了个号  
![QQ截图20210918121957](https://user-images.githubusercontent.com/90946710/133870855-adff50e7-d635-450b-b94f-3ce1d72ff6bd.png)
![QQ图片20210918115622](https://user-images.githubusercontent.com/90946710/133870856-2860d7d2-e1d2-4682-bdc2-b94153865e71.png)

**Comment by dipoo** [comment]
@guhuibanfan-ex 封面确实没解析出来，估计网站改动了

**Comment by guhuibanfan-ex** [comment]
> @guhuibanfan-ex 封面确实没解析出来，估计网站改动了

感谢大佬 不是我的问题就好

**Comment by dipoo** [comment]
@guhuibanfan-ex 更新脚本

**Comment by guhuibanfan-ex** [comment]
> @guhuibanfan-ex 更新脚本
问题已解决 感谢大佬

**Comment by UdongeinL** [comment]
感谢大佬，更新之前老任务可以继续而新任务没法创建，更新后可以创建新任务了（虽然我被403了）
